name: Micro-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Microservices-CI:
  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        microservice: ["auth", "production", "promptify", "prompts"]

    steps:
      - name: Checkout Microservices Code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ matrix.microservice }}/package-lock.json

      - name: Install Dependencies Of Microservice ${{ matrix.microservice }}
        working-directory: ${{ matrix.microservice }}
        run: npm ci

      - name: Build Microservice ${{ matrix.microservice }}
        working-directory: ${{ matrix.microservice }}
        run: npm run build --if-present

      - name: Test Microservice ${{ matrix.microservice }}
        working-directory: ${{ matrix.microservice }}
        run: npm test --if-present
      
